/*******************************************************************************
 * Copyright (C) 2013 Andrei Olaru, Vlad Herescu, Cristian Neagoe, Cristian Grigoras
 * 
 * This file is part of AmIciTy-incubator-Android.
 * 
 * AmIciTy-incubator-Android is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
 * 
 * AmIciTy-incubator-Android is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with AmIciTy-incubator-Android.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/

package net.amicity.common.context_types;

import net.amicity.common.core.ContextTypes;

/**
 * This class represents a sound item, generated by the sound module. It has a
 * double which retains the level of sound.
 * 
 * @author ''Azgabast''
 * 
 */
public class SoundItem extends AbstractItem {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * The maximum noise heard in the last interval.
	 */
	double value;

	/**
	 * @param value
	 *            The sound level returned by the device microphone during the
	 *            last listening interval.
	 */
	public SoundItem(double value) {
		this.value = value;
		this.type = ContextTypes.SOUND_CONTEXT;
	}
	
	/**
	 * @return The sound value.
	 */
	public double getValue() {
		return value;
	}
}
