package net.amicity.common.context_types;

import net.amicity.common.core.ContextItem;
import net.amicity.common.core.ContextTypes;

/**
 * This class represents a sound item, generated by the sound module. It
 * has a double which retains the level of sound.
 * @author ''Azgabast''
 *
 */
public class SoundItem implements ContextItem
{
	/**
	 * The maximum noise heard in the last interval.
	 */
	double value;
	/**
	 * The type of this context item.
	 */
	ContextTypes type;
	
	/**
	 * @param value The sound level returned by the device microphone during
	 * the last listening interval.
	 */
	public SoundItem(double value) {
		this.value = value;
		this.type = ContextTypes.SoundContext;
	}
}
